services:
  - type: web
    name: eventhub-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://bhavishya:bhavishya123@cluster0.77o0gwf.mongodb.net/test
      - key: JWT_SECRET
        value: your_super_secret_jwt_key_here_make_it_long_and_random
      - key: JWT_EXPIRE
        value: 7d
      - key: CLOUDINARY_CLOUD_NAME
        value: dqvpxwxsf
      - key: CLOUDINARY_API_KEY
        value: 132891492545351
      - key: CLOUDINARY_API_SECRET
        value: s6nTALvlo8uNQJ1OhvEp1GA_LUs
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: sourabhkhadav2@gmail.com
      - key: EMAIL_PASS
        value: ghekitfcdmxsfogb
      - key: FRONTEND_URL
        value: https://eventhub-lovat.vercel.app/
